static const char *stringHours[] = {
    "dotze",
    "una",
    "dues",
    "tres",
    "quatre",
    "cinc",
    "sis",
    "set",
    "vuit",
    "nou",
    "deu",
    "onze",
    "dotze",
    "una"
};

static const char *stringHourParts[] = {
    "",
    "han tocat",
    "han tocat",
    "han tocat",
    "han tocat",
    "mig quart",
    "mig quart",
    "mig quart",
    "mig quart",
    "mig quart",
    "mig quart",
    "mig quart",
    "vora un quart",
    "vora un quart",
    "vora un quart",
    "un quart",
    "un quart tocat",
    "un quart tocat",
    "un quart tocat",
    "un quart tocat",
    "un quart i mig",
    "un quart i mig",
    "un quart i mig",
    "un quart i mig",
    "un quart i mig",
    "un quart i mig",
    "un quart i mig",
    "vora dos quarts",
    "vora dos quarts",
    "vora dos quarts",
    "dos quarts",
    "dos quarts tocats",
    "dos quarts tocats",
    "dos quarts tocats",
    "dos quarts tocats",
    "dos quarts i mig",
    "dos quarts i mig",
    "dos quarts i mig",
    "dos quarts i mig",
    "dos quarts i mig",
    "dos quarts i mig",
    "dos quarts i mig",
    "vora tres quarts",
    "vora tres quarts",
    "vora tres quarts",
    "tres quarts",
    "tres quarts tocats",
    "tres quarts tocats",
    "tres quarts tocats",
    "tres quarts tocats",
    "tres quarts i mig",
    "tres quarts i mig",
    "tres quarts i mig",
    "tres quarts i mig",
    "tres quarts i mig",
    "cinc minuts per",
    "vora",
    "vora",
    "vora",
    "vora"
};

char* concat(const char *s1, const char *s2);
char* hour_to_string(int hour, int min);
const char* part_time_to_string(int hour, int min);
